### ISSUE TITLE
Queries regarding the IFCtoLBD converter

### ISSUE THREAD

**Issue by AJAY31797** [jyrkioraskari/IFCtoLBD#104]
Hi Team, 

I am a researcher trying to use the IFCtoLBD converter to convert an IFC file (containing information about a 4D BIM) to RDF for some of my research work. I used the latest version (IFCtoLBD_Desktop_2024) to convert an IFC file to LBD. I had a few queries regarding the results. It would be a great help if you could answer them. 

1. The geometry of the building elements, as represented in the resulting LBD file, looks something like this:
![image](https://github.com/jyrkioraskari/IFCtoLBD/assets/53423573/98bfd28b-8591-4f2d-8ea5-637b26a435f5)

Do the coordinates represented in the multipoint signify the two diagonally opposite coordinates of the bounding box? I remember the earlier version used to provide the Xmin, Xmax, Ymin, Ymax, Zmin, and Zmax coordinates separately. So, are the coordinates provided in the multipoint just (Xmin, Ymin, Zmin) and (Xmax, Ymax, Zmax)?

2. To my understanding, the elements are connected to bounding boxes using a property lbd:containsInBoundingBox, as shown below.
![image](https://github.com/jyrkioraskari/IFCtoLBD/assets/53423573/ffd44c66-c627-4656-a709-430cb9fd9452)

Am I correct in interpreting this? If yes, why are there more objects than objects in this property (this would mean that there is more than one bounding box for the same object)? If not, what exactly is lbd:containsInBoundingBox doing?

3. Are the bounding boxes axis aligned?

4. What does the prefix 'lbd' refer to? Which ontology is it connecting with? The URI given in the generated LBD file is @Prefix lbd: https://linkedbuildingdata.org/LBD#. Searching this link leads to nowhere; it shows the DNS address not found. (I have raised this query earlier as well).

5. In the UI of the converter, I see this option called "Include IFC Based Elements" (screenshot attached). What exactly does it do differently from the "Create and link ifcOWL" option?
 
![image](https://github.com/jyrkioraskari/IFCtoLBD/assets/53423573/440d43a5-8fe7-42cc-ad39-d4522d01b4a4)

Thanks in advance,
Ajay

**Comment by VladimirAlexiev** [comment]
@jyrkioraskari , @maximelefrancois86 feedback?

1. Yes.  But check coordinates for reasonableness. See https://github.com/jyrkioraskari/IFCtoLBD/issues/98 and https://github.com/jyrkioraskari/IFCtoLBD/issues/97
2. `x lbd:containsInBoundingBox y` means that x is "bigger" than y and BB(x) includes BB(y), so it can be multivalued
    - I think it's ok to have a beam within the volume of a wall
    - But a second wall within the volume of the first wall? That is doubtful
3. I think it uses "mm" for the coordinates, and they are aligned along the building axes.
  I suspect they are not geo-referenced, i.e. not northing/easting.
  I don't know of any northing/easting CRS to use "mm", they all use "m".
  Not being geo-referenced is a major problem for any land-use related case
4. `lbd` is made-up on the spot. 
    - `lbd` is not one ontology but a community group with many specific ontologies
    - The only other place on earth where this prop appears is in this question:
      https://stackoverflow.com/questions/77205257/incorrect-result-in-shacl-validation
    - This said, it's ok to use RDF without ontologies: they are nice but optional

**Comment by VladimirAlexiev** [comment]
@AJAY31797 Is that your question on StackOverflow? I posted an answer: https://stackoverflow.com/questions/77205257/incorrect-result-in-shacl-validation/78322960#78322960

**Comment by AJAY31797** [comment]
Many Thanks, @VladimirAlexiev, for the response. Yes, that query on StackOverflow was mine. Sorry if my questions seem silly; I am new to this field and trying to understand the concepts.  
Thanks for the answers again.
