### ISSUE TITLE
How are the GUIDs generated for RDF?

### ISSUE THREAD

**Issue by k----n** [jyrkioraskari/IFCtoLBD#14]
A lot of code to go through...

It doesn't seem like "IfcRoot" is used in naming the nodes for RDF.
Instead, a GUID is used which I cannot be linked back to the original IFC.

Is this supposed to happen?

**Comment by mathib** [comment]
Each ABox node that's the result of converting instances from an IFC file that have an IFC GUID (= all instances of bot:Element or bot:Zone) have a unique URI (~ ID) that's a combination of the URI base set by the user, a short string indicating the BOT (in the case of bot:Zone) or PRODUCT class (in the case of bot:Element) and ending with the IFC GUID (but in another encoding). The IFC files contain either compressed strings representations of IFC GUIDs. The converter only uses uncompressed GUIDs, so any compressed IFC GUID is represented in it's uncompressed form. See buildingSMART website for more information: http://www.buildingsmart-tech.org/implementation/get-started/ifc-guid

With the default base URI, the following IFC building element (example taken from the Duplex house):

`#6652=IFCDOOR('1hOSvn6df7F8_7GcBWlRGQ',#33,'M_Single-Flush:1250mm x 2010mm:1250mm x 2010mm:146596',$,'1250mm x 2010mm',#6651,#6646,'146596',2.009999999999999,1.25);`

is transformed into an ABox node:
`https://www.ugent.be/myAwesomeFirstBIMProject#` + `_` + `door` +  `_` + `6b61ce71-1a7a-473c-8f87-4262e0bdb41a`
(or in short, when using prefixes: `inst:door_6b61ce71-1a7a-473c-8f87-4262e0bdb41a`)

If you want to have access to the compressed IFC GUID as it was formatted originally, you have to select PROPERTIES during the conversion, and then you will get the following triples:
```
inst:door_6b61ce71-1a7a-473c-8f87-4262e0bdb41a
        a                             be:Door , bot:Element ;
        props:batid_attribute_simple  "146596" ;
        props:fireRating_simple       "Fire Rating" ;
        props:globalIdIfcRoot_attribute_simple
                "1hOSvn6df7F8_7GcBWlRGQ" ;
        ...
```
The original IFC GUID representation can be found as the value of `props:globalIdIfcRoot_attribute_simple`
