### ISSUE TITLE
IfcRelAggregates not converting

### ISSUE THREAD

**Issue by pipauwel** [jyrkioraskari/IFCtoLBD#16]
In some IFC files, the relation between Site, Building, Storey, and Space are "IfcRelAggregates" relationships. The current code only looks for "IfcRelDecomposes" relations. As a result, the IFCtoLBD code only converts the IfcSite of the IFC building. 

See line number 669 in IFCtoLBDConvert.java

Example file for testing: https://github.com/xBimTeam/XbimSamples/blob/master/ExcelReportExample/SampleHouse.ifc

**Comment by simonstey** [comment]
#8 possibly related

**Comment by jyrkioraskari** [comment]
This was fixed in #8. I tested the example file and Building and Storey elements were listed. 

The current output is attached. 
output_ttl.txt](https://github.com/jyrkioraskari/IFCtoLBD/files/5311098/output_ttl.txt)
