### ISSUE TITLE
IFC property sets are not converted in +v1.71

### ISSUE THREAD

**Issue by mathib** [jyrkioraskari/IFCtoLBD#18]
The conversion of properties in PSETs is failing since +v1.71
Direct properties (attributes) are still converted correctly.

**Comment by jyrkioraskari** [comment]
This should be fixed now. Please confrm.

**Comment by mathib** [comment]
works now for the Duplex house. Did you tested this on different IFC versions? 

Would be good if there was some kind of unit testing in the future :)
