### ISSUE TITLE
check IFC schema version and keep out any uncommon IFC schemas

### ISSUE THREAD

**Issue by pipauwel** [jyrkioraskari/IFCtoLBD#2]
There are very old IFC files which should not be supported. So, an IFC version check needs to be implemented near the beginning of upload. 

Example file: http://smartlab1.elis.ugent.be:8889/IFC-repo/http.openifcmodel.cs.auckland.ac.nz/05111002_IFCR2_Geo_Columns_1.ifc

Error received: 
nl.tue.ddss.convert.IfcVersionException: Cannot determine which IFC version the model it is: [IFC20_LONGFORM]

**Comment by jyrkioraskari** [comment]
An early check was added,  This is fixed in version 2.8.
