### ISSUE TITLE
option to not write ifcOWL graph

### ISSUE THREAD

**Issue by mathib** [jyrkioraskari/IFCtoLBD#25]
I believe the current option to export the ifcOWL graph from the IFC-to-RDF converter, besides the LBD graph(s), is overkill in many situations. Maybe an option in the UI could be provided for users to select if they really want an additional ifcOWL output graph?

**Comment by mathib** [comment]
+ if the ifcOWL output is not materialized, the `owl:sameAs` links in the output LBD graphs can be left out.

**Comment by jyrkioraskari** [comment]
I strongly agree here. In the last two years, at least three persons have asked for the interlinking feature. It was easy to add, but it is pretty useless without a companying ifcOWL model or an ifcOWL model with a known base URI.
However, the additional file may cause confusion, and there should be no undocumented features in the software.  So, as you suggested, an option on the user interface with the default value as off would be fine.

**Comment by jyrkioraskari** [comment]
It is optional  now.
