### ISSUE TITLE
IFC Virtual Elements not found

### ISSUE THREAD

**Issue by pipauwel** [jyrkioraskari/IFCtoLBD#4]
The code does not know what to do with IfcVirtualElement, because no virtual elements are available in the BOT, PRODUCT, PROPS ontology. 

As it seemingly makes little sense to model virtual things, I suggest to drop this information in the conversion, considering it is in the IFC anyway if needed.

Example file: 
http://smartlab1.elis.ugent.be:8889/IFC-repo/IFC_Schependomlaan.ifc

Error:
No type: https://dot.ugent.be/IFCtoLBDset#IfcVirtualElement_1063273

**Comment by jyrkioraskari** [comment]
Indeed, it was an unnecessary warning to show that we had elements that did not belong to the ontologies and were not handled. 
This feature is removed in version 2.8.
