### ISSUE TITLE
DockerFile - Java version bug

### ISSUE THREAD

**Issue by wojciechteclaw** [jyrkioraskari/IFCtoLBD#41]
While posting an IFC file following message with HTTP 500 is returned:

</head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> Servlet.init() for servlet [jersey-serlvet] threw exception</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>javax.servlet.ServletException: Servlet.init() for servlet [jersey-serlvet] threw exception
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base&#47;java.lang.Thread.run(Thread.java:829)
</pre><p><b>Root Cause</b></p><pre>java.lang.UnsupportedClassVersionError: de&#47;rwth_aachen&#47;dc&#47;ifc2lbd&#47;rest&#47;IFCtoLBD_OpenAPI has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0 (unable to load class [de.rwth_aachen.dc.ifc2lbd.rest.IFCtoLBD_OpenAPI])
	org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2483)
	org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:870)
	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1371)
	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1215)
	java.base&#47;java.lang.Class.forName0(Native Method)
	java.base&#47;java.lang.Class.forName(Class.java:398)
	org.glassfish.jersey.internal.util.ReflectionHelper$7.run(ReflectionHelper.java:379)
	org.glassfish.jersey.internal.util.ReflectionHelper$7.run(ReflectionHelper.java:374)
	java.base&#47;java.security.AccessController.doPrivileged(Native Method)
	org.glassfish.jersey.server.internal.scanning.AnnotationAcceptingListener$AnnotatedClassVisitor.getClassForName(AnnotationAcceptingListener.java:286)
	org.glassfish.jersey.server.internal.scanning.AnnotationAcceptingListener$AnnotatedClassVisitor.visitEnd(AnnotationAcceptingListener.java:209)
	jersey.repackaged.org.objectweb.asm.ClassReader.accept(ClassReader.java:747)
	jersey.repackaged.org.objectweb.asm.ClassReader.accept(ClassReader.java:423)
	org.glassfish.jersey.server.internal.scanning.AnnotationAcceptingListener$ClassReaderWrapper.accept(AnnotationAcceptingListener.java:323)
	org.glassfish.jersey.server.internal.scanning.AnnotationAcceptingListener$ClassReaderWrapper.access$200(AnnotationAcceptingListener.java:304)
	org.glassfish.jersey.server.internal.scanning.AnnotationAcceptingListener.process(AnnotationAcceptingListener.java:151)
	org.glassfish.jersey.server.ResourceConfig.scanClasses(ResourceConfig.java:920)
	org.glassfish.jersey.server.ResourceConfig._getClasses(ResourceConfig.java:864)
	org.glassfish.jersey.server.ResourceConfig.getClasses(ResourceConfig.java:773)
	org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.&lt;init&gt;(ResourceConfig.java:1216)
	org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.&lt;init&gt;(ResourceConfig.java:1187)
	org.glassfish.jersey.server.ResourceConfig.createRuntimeConfig(ResourceConfig.java:1183)
	org.glassfish.jersey.server.ApplicationHandler$RuntimeConfigConfigurator.init(ApplicationHandler.java:184)
	org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$0(ApplicationHandler.java:294)
	java.base&#47;java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:294)
	org.glassfish.jersey.server.ApplicationHandler.&lt;init&gt;(ApplicationHandler.java:261)
	org.glassfish.jersey.servlet.WebComponent.&lt;init&gt;(WebComponent.java:311)
	org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
	org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base&#47;java.lang.Thread.run(Thread.java:829)
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/9.0.58</h3></body></html>

**Comment by jyrkioraskari** [comment]
Hey,

I recompied it with  JDK17.  At least it works here in the tests. 
docker container run -it --publish 8081:8080 jyrkioraskari/ifc2lbdopenapi
http://localhost:8081/IFCtoLBD_OpenAPI/apidocs/
