### ISSUE TITLE
file conversion error: "-1.#IND" is not a double

### ISSUE THREAD

**Issue by pipauwel** [jyrkioraskari/IFCtoLBD#6]
There is an error in the resulting file. Namely, something that is not a double is converted into a double. Can you check?

See below:

inst:beam_8cef57ab-c6fe-41bc-9c22-611eec72a1ba props:slope_simple            "-1.#IND"^^xsd:double ;

The example file is:
http://smartlab1.elis.ugent.be:8889/IFC-repo/20151023_TeklaBIMAwards2014/wereld_van_theater_en_wereld_van_ontmoeting/550c78cf-f683-4da6-8253-b1ef0a01010e.ifc

**Comment by jyrkioraskari** [comment]
Hey, 

The IFC file contains the following:
#3743013=IFCBEAM('2CxrUhnlv1l9mYOHxiSg6w',#41,'300_28_lbc_balk_koker:K100/4:4545168',$,'300_28_lbc_balk_koker:K100/4:804710',#3742778,#3743011,'4545168');
#3743030= IFCRELDEFINESBYPROPERTIES('1NN1p2TxvBxw3mssjSOS9X',#41,$,$,(#3743013),#3743028);
#3743028= IFCPROPERTYSET('2CxrUhnlv1l9mYQlViSg6w',#41,'Pset_BeamCommon',$,(#5437,#5438,#3632402,#3743026,#3743027));
#5437= IFCPROPERTYSINGLEVALUE('LoadBearing',$,IFCBOOLEAN(.T.),$);
#5438= IFCPROPERTYSINGLEVALUE('IsExternal',$,IFCBOOLEAN(.F.),$);
#3632402= IFCPROPERTYSINGLEVALUE('Reference',$,IFCIDENTIFIER('300_28_lbc_balk_koker:K100/4'),$);
#3743026= IFCPROPERTYSINGLEVALUE('Span',$,IFCPOSITIVELENGTHMEASURE(3180.),$);
#3743027= IFCPROPERTYSINGLEVALUE('Slope',$,IFCPLANEANGLEMEASURE(-1.#IND),$);

TYPE IfcPlaneAngleMeasure = REAL;
END_TYPE;

It seems to be defined of data type real.  What of the RDF data types should it be?
https://www.w3.org/2011/rdf-wg/wiki/XSD_Datatypes

**Comment by jyrkioraskari** [comment]
"Windows displays a NaN as -1.#IND ("IND" for "indeterminate") while Linux displays nan."
So, the correct value should be "NaN"^^xsd:double (ref. https://docstore.mik.ua/orelly/xml/schema/ch04_04.htm)
This is fixed in this way:
if(pvalue.isLiteral())
{
  String val=pvalue.asLiteral().getLexicalForm();
  if(val.equals("-1.#IND"))
    pvalue=ResourceFactory.createTypedLiteral(Double.NaN);
}

Result: NaN^^http://www.w3.org/2001/XMLSchema#double

**Comment by mathib** [comment]
@jyrkioraskari I wouldn't go this way as the resulting RDF might give errors while entering an RDF triplestore that's picky about the RDF datatype. From the RDF perspective, the literal 'NaN' is a string and not a double... The simplest solution is to not convert this IFC line to RDF? BTW: what does the IFCtoRDF (ifcOWL) converter in the above case?

**Comment by jyrkioraskari** [comment]
I accept the point.  Although, NaN seems to be a valid value in the RDF 1.1 context:  https://www.w3.org/TR/rdf11-concepts/#xsd-datatypes, the meaning of removing the triple should be the same. There should be no need to use a triple to indicate that the information is non-existent, i.e. undefined.  If needed add this feature back, the Jena ResourceFactory.createTypedLiteral(Double.NaN) should be a usable solution.    This will be in version 2.8.
