### ISSUE TITLE
IfcRelAggregates vs. IfcRelDecomposes for different IFC versions

### ISSUE THREAD

**Issue by simonstey** [jyrkioraskari/IFCtoLBD#8]
Methods `listBuildings`,`listStoreys`,`listStoreySpaces` use **IfcRelDecomposes** to navigate through the hierarchy:
https://github.com/jyrkioraskari/IFCtoLBD/blob/f86efd5acbf47da8743fd91dd7e21b30566afef1/converter/src/main/java/org/lbd/ifc2lbd/IFCtoLBDConverter.java#L611-L635

requiring aggregates like the following to be able to get from a specific IFCSite to all of its IFCBuildings:
```turtle
inst:IfcRelAggregates_533237
        a                         ifc:IfcRelAggregates ;
        [...]
        ifc:relatedObjects_IfcRelDecomposes inst:IfcBuilding_122 ;
        ifc:relatingObject_IfcRelDecomposes inst:IfcSite_532825 .
```
however, this does not work for IFC versions newer than 2x3, because starting from [IFC2x4](http://www.buildingsmart-tech.org/ifc/IFC2x4/rc2/html/schema/ifckernel/lexical/ifcrelaggregates.htm):
> IFC2x4 CHANGE The attributes RelatingObject and RelatedObjects are demoted from the supertype IfcRelDecomposes

which also holds true for [IFC4](http://www.buildingsmart-tech.org/ifc/IFC4/final/html/link/ifcrelaggregates.htm):
> IFC4 CHANGE The attributes RelatingObject and RelatedObjects are demoted from the supertype IfcRelDecomposes.

resulting in `ifc:IfcRelAggregates` being expressed as follows:
```turtle
inst:IfcRelAggregates_85449
        a                         ifc:IfcRelAggregates ;
        [...]
        ifc:relatedObjects_IfcRelAggregates inst:IfcBuilding_130 ; # property changed
        ifc:relatingObject_IfcRelAggregates inst:IfcSite_84992 . # property changed
```
and consequently, aforementioned methods not being able to traverse through the hierarchy at all.

----------
### Solution

one way to fix this issue would be to e.g., make the IFCVersion global and choose the path to take for traversing accordingly:

```java
private RDFStep[] getNextLevelPath(){
	if (version.getLabel().indexOf("IFC2X3") != -1){
		RDFStep[] path = { new InvRDFStep(ifcOWL.getRelatingObject_IfcRelDecomposes()),
				new RDFStep(ifcOWL.getRelatedObjects_IfcRelDecomposes()) };
		return path;
	} else {
		RDFStep[] path = { new InvRDFStep(ifcOWL.getProperty("relatingObject_IfcRelAggregates")),
				new RDFStep(ifcOWL.getProperty("relatedObjects_IfcRelAggregates")) };
		return path;
	}
}

private List<RDFNode> listBuildings(Resource site) {
	return pathQuery(site, getNextLevelPath());
}
```

**Comment by jyrkioraskari** [comment]
Thank you.  Your solution was added
