### ISSUE TITLE
listPropertysets only works for IFC version 2x3

### ISSUE THREAD

**Issue by simonstey** [jyrkioraskari/IFCtoLBD#9]
Similar to Issue #8, method `listPropertysets` uses a hardcoded path to get from objects to their property sets. However, used path is only valid for [IFC2x3 and below](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/):
https://github.com/jyrkioraskari/IFCtoLBD/blob/f86efd5acbf47da8743fd91dd7e21b30566afef1/converter/src/main/java/org/lbd/ifc2lbd/IFCtoLBDConverter.java#L732-L736

requiring IfcRelDefinesByProperty definitions like the following:
```turtle
inst:IfcRelDefinesByProperties_42475
        a                         ifc:IfcRelDefinesByProperties ;
        [...]
        ifc:relatedObjects_IfcRelDefines
                inst:IfcDistributionControlElement_42436 ; 
        ifc:relatingPropertyDefinition_IfcRelDefinesByProperties 
                inst:IfcPropertySet_42472 . 
```
But, this does not work for IFC versions newer than 2x3, because starting from [IFC2x4](http://www.buildingsmart-tech.org/ifc/IFC2x4/rc2/html/schema/ifckernel/lexical/ifcreldefinesbyproperties.htm):
> IFC2x4 CHANGE The attribute RelatedObjects had been demoted from the supertype IfcRelDefines to IfcRelDefinesByProperties.

resulting in `ifc:IfcRelDefinesByProperties` being expressed as follows:
```turtle
inst:IfcRelDefinesByProperties_42475
        a                         ifc:IfcRelDefinesByProperties ;
        [...]
        ifc:relatedObjects_IfcRelDefinesByProperties # property changed
                inst:IfcDistributionControlElement_42436 ; 
        ifc:relatingPropertyDefinition_IfcRelDefinesByProperties # property changed
                inst:IfcPropertySet_42472 . 
```
and consequently, method `listPropertysets` not being able to retrieve any property sets at all.

----------
### Solution

similar to the proposed fix for #8: 

```java
private RDFStep[] getPropertySetPath(){
	if (version.getLabel().indexOf("IFC2X3") != -1){
		RDFStep[] path = { new InvRDFStep(ifcOWL.getRelatedObjects_IfcRelDefines()),
				new RDFStep(ifcOWL.getRelatingPropertyDefinition_IfcRelDefinesByProperties()) };
		return path;
	} else {
		RDFStep[] path = { new InvRDFStep(ifcOWL.getProperty("relatedObjects_IfcRelDefinesByProperties")),
				new RDFStep(ifcOWL.getProperty("relatingPropertyDefinition_IfcRelDefinesByProperties")) };
		return path;
	}	
}

private List<RDFNode> listPropertysets(Resource resource) {
	return pathQuery(resource, getPropertySetPath());
}
```

**Comment by jyrkioraskari** [comment]
Thank you. Your solution was added.
