### ISSUE TITLE
are geometries always represented as EXPRESS lists?

### ISSUE THREAD

**Issue by VladimirAlexiev** [jyrkioraskari/IFCtoLBD#94]
Hi @jyrkioraskari and @maximelefrancois86 !
A stupid question: does this convert geometries to the dreaded  EXPRESS lists as per IFCowl, or to a more practical representation similar to GeoSPARQL?

I ran IFCtoLBD_Desktop_2024.jar (run_2024.bat from the latest release) with default options:
![image](https://github.com/jyrkioraskari/IFCtoLBD/assets/536250/53bf0ba0-408a-465e-9226-7e609a6a76e3)

And I got stuff like this:
```ttl
inst:REAL_List_219311
        rdf:type  express:REAL_List .

inst:REAL_219312  rdf:type  express:REAL ;
        express:hasDouble  "1."^^xsd:double .

inst:REAL_List_219309
        list:hasContents  inst:REAL_219312 ;
        list:hasNext      inst:REAL_List_219310 .

inst:REAL_219313  rdf:type  express:REAL ;
        express:hasDouble  "0."^^xsd:double .

inst:REAL_List_219310
        list:hasContents  inst:REAL_219313 ;
        list:hasNext      inst:REAL_List_219311 .
```
Should I change some options, or maybe I need to use the command line https://github.com/jyrkioraskari/IFCtoLBD#command-line-usage ?

**Comment by jyrkioraskari** [comment]
For practical reasons, we have both presentations. On the user interface, select "Bounding Boxes as WKT". Please, comment if you find inconsistencies there. 

I updated the command line user interface to include the --hasWKT, --hasHierarchicalNaming, and --hasPerformanceBoost options. So,  --hasWKT should give you the GeoSPARQL version.  The change was added to the source code. I will provide the compiled version in the next release.

**Comment by VladimirAlexiev** [comment]
Thanks @jyrkioraskari ! What does the WKT include: floor plans with Z coordinates for each floor?
cc @nataschake.

**Comment by jyrkioraskari** [comment]
Thank you!  The  --ifcOWL description is fixed.

By default, the 3D WKT bounding boxes are created for all BIM elements that have geometry. Most of the models have elevation properties for the floors. The floor plans shown on the repository were created using the element's OBJ property and the intersection calculation with the plane, which offers the full 2D geometry connected to the elements.

**Comment by nataschake** [comment]
@jyrkioraskari @pipauwel 

Hi! 
Is there any particular sense in having
```
rdf:type                   beo:Member ;
rdf:type                   beo:Member-STRINGER ;
```
in one instance definition?
I also met 
`rdf:type                   beo:Wall-NOTDEFINED ;`
(parameters: generate and link ifcOWl - no, PROPS - level1, Generate geometry - yes, Bounding boxes as WKT - yes)

**Comment by VladimirAlexiev** [comment]
Jyrki, thanks! I'll close this one, but I think the options can be **explained better**.

We'll experiment more, raise further issues, and report experience.
BTW will you be at OGC's Digital Building Permit conference in Barcelona in about 2 weeks?

@nataschake OPEN SEPARATE issues! Don't lump all kind of stuff into this issue.
