### ISSUE TITLE
wrong xsd:base64Binary namespace

### ISSUE THREAD

**Issue by VladimirAlexiev** [jyrkioraskari/IFCtoLBD#95]
```ttl
@prefix xsd: <https://www.w3.org/2001/XMLSchema#> .

        fog:asObj_v3.0-obj  "..."^^<https://www.w3.org/TR/xmlschema-2/#base64Binary> ;
```
The reason the datatype URL is not shortened is because it uses a wrong (versioned) namespace rather than `xsd`

**Comment by jyrkioraskari** [comment]
Thank you!  Yes,  you are right.  The https://www.w3.org/TR/xmlschema-2/ should not be used and the format was wrong. Fixed now.
